### ISSUE TITLE
build 32-bit binary on Apple Silicon Mac

### ISSUE THREAD

**Issue by chris-pn-dev** [below/HelloSilicon#32]
Hi,
    Is it possible to build your examples into 32-bit binary and run on Apple Silicon Mac? If yes, what's the build command? Thanks!

**Comment by chris-pn-dev** [comment]
Because I has only one ARM device (Apple Silicon Mac) for development, and I want to try both 32bit and 62bit arm assembly. I'm appreciate if you can help to give the answer.

**Comment by below** [comment]
You will not be able to build runnable ARM 32 executables on the M1. You can build executables for the Apple Watch 3, or for older iPhones. 
For ARM 32, I really would recommend getting a cheap Raspberry Pi 2 (or even 1).

**Comment by chris-pn-dev** [comment]
Thanks for your answer. I'll close this issue.
